config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  # Create all the needed routes e.g recipes#new
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show] 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :like]
  before_action :require_user, except: [:show, :index, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end
  
  def show

  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully"
      # Redirect to recipe index action
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  # routes for edit recipes/:id/edit
  def edit

  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Selection successful"
      redirect_to :back
    else
      flash[:danger] = "You can only like or dislike a recipe once"
      redirect_to :back
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe Deleted"
    redirect_to recipes_path
  end

  private
    
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids:[])
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def require_same_user
      if current_user != @recipe.chef and !current_user.admin?
        flash[:danger] = "You can only edit your own recipe"
        redirect_to recipes_path
      end
    end
    
  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end
  end
  
  def admin_user
    redirect_to recipes_path unless current_user.admin?
  end
  
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <!--Build rails form-->
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>      
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %> 
      
      <strong>Styles:</strong>
      <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
      <br><br>
      <strong>Ingredients:</strong>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
        <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
      <% end %>
      <br><br>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
      </span>
      
      <!--Change depending on new or edit recipe-->
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<!--Query validation for the image size-->
<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Choose smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<!--Pagination-->
<%= will_paginate %>

<!--Iterate through all the recipes-->
<% @recipes.each do |recipe| %>
  <div class="row">
    
    <div class="col-md-2">
      <!--Add styling for chef_info at custom.css.scss-->
      <section class="chef_info center">
        <!--Get the chef associated with the recipe-->
        <!--Create the gravatar_for method on application_helper-->
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef name: <%= recipe.chef.name %></h5>
      </section>
    </div>
    
    <!--Contents of the recipe-->
    <div class="col-md-6 well">
      <!--Give the recipe name link a path-->
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <!--render a style partial-->
      <% if recipe.styles.any? %>
        <p>Styles: <%= render recipe.styles %></p>
      <% end %>
      <!--render an ingredient partial-->
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class='quiet'><small> created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class='quiet'><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <!--Show like icon-->
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
        <!--Show dislike icon-->
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    <!--Image of recipe-->
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
  </div>
  <!--Add horizontal line after each recipe-->
  <hr/>
<% end %>

<!--Pagination-->
<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a New Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <!--Image of chef from email address gravatar-->
  <div class="col-md-4 pull-right center">
    <!--Clicking on the chef image takes you to chef profile-->
    <%= link_to gravatar_for(@recipe.chef, size: 150), chef_path(@recipe.chef)%>
    <p>
      <h5>Brought to you by: <%= @recipe.chef.name %></h5>
    </p>
  </div>
  
  <div class="col-md-8">
    <!--Show only the recipe if the recipe belongs to current user or admin-->
    <% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
      <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>
    <!--Only admin can delete a recipe-->
    <% if logged_in? and current_user.admin? %>
      <%= link_to "Delete Recipe", @recipe, method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    
    <!--Image of recipe-->
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    
    <div class="well">
      <% if @recipe.styles.any? %>
        <p>Styles: <%= render @recipe.styles %></p>
      <% end %>
      <% if @recipe.ingredients.any? %>
        <p>Ingredients: <%= render @recipe.ingredients %></p>
      <% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <!--Show like icon-->
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
        <!--Show dislike icon-->
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--Add link to return to recipe index, to verify rake routes recipes should go to #index action-->
<h5><%= link_to 'Return to Recipe Listing', recipes_path, class: "btn btn-warning btn-small" %></h5>