config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  # Create all the needed routes e.g recipes#new
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show] 
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  
  <h2>Homepage for ROR course on UDEMY</h2>
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-md-4">
    <h3 class="midrow">
      Browse Recipes as Guest
    </h3>
    <h2 class="left">Browse recipes as a guest</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
    
  <div class="col-md-4">
    <h3 class="midrow">
      Sign in to you account
    </h3>
    <h2 class="left">Add/Update your recipes/reviews</h2>
    <p><%= link_to "Login to you account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
    
  <div class="col-md-4">
    <h3 class="midrow">
      Browse Recipes as Guest
    </h3>
    <h2 class="left">Browse recipes as a guest</h2>
    <p><%= link_to "Browse Recipe Listings","", class: "btn btn-warning btn-small" %></p>
  </div>
</div>